### ISSUE TITLE
 request:fail response data convert to utf8 fail

### ISSUE THREAD

**Issue by lizhiyao** [rchunping/wxapp-google-analytics#1]
使用 wxapp-google-analytics 打点方案，

在 Mac 开发者工具上，打点时报错：request:fail 小程序要求的 TLS 版本必须大于等于 1.2。

在 iPhone 6，IOS 10.2，Wechat 6.5.3 上，报错： request:fail response data convert to utf8 fail。

去看 ga.js 的源码，报错时请求的地址为：https://www.google-analytics.com/collect

**Comment by rchunping** [comment]
@lizhiyao TLS的问题，翻墙的时候我也碰到了，你可以在开发者工具设置里先禁止TLS检查。

第二个问题没碰到，正常返回其实是一张1x1像素的gif图片

能把大致的HitBuilder上设置的参数贴上来吗？

**Comment by rchunping** [comment]
@lizhiyao 用iPhone测试了以下，确实如你所说。

这应该是iPhone上微信小程序接口的bug，始终把返回当成json数据了。wx.request设置 header:{"accept":"image/*"} 无效，尝试了dataType: text 也无效

不过实际上不影响数据上报，数据已经发送给谷歌了。

你可以打开谷歌统计后台，看 实时/概览 ，能看到数据的。

**Comment by rchunping** [comment]
感谢反馈，已经在文档中说明。

**Comment by lizhiyao** [comment]
以上两种请求报错，确实不影响数据成功发送给谷歌。在 GA 后台可以看到统计结果。

感谢！
