### ISSUE TITLE
“Google Analytics（分析）服务 SDK 将停用”是否会影响相关功能？

### ISSUE THREAD

**Issue by zohoMatt** [rchunping/wxapp-google-analytics#11]
感谢作者提供package，很有帮助

最近收到邮件，之处2019年10月Google Analytics服务 SDK 将停用
https://support.google.com/analytics/answer/9167112?hl=zh-Hans

请问停止服务后，wxapp-google-analytics功能还能正常使用嘛？

**Comment by rchunping** [comment]
应该不影响，通知里提到sdk停用不包括 "通过Measurement Protocol 收集数据"
