### ISSUE TITLE
想要请教一下如果已存在网站的情况下新增小程序是再新增一个媒体资源吗？

### ISSUE THREAD

**Issue by algery** [rchunping/wxapp-google-analytics#14]
已经使用GA统计网站数据，那么现在开发小程序使用GA统计是新增一个媒体资源还是放在同一个媒体资源里？我现在的想法更倾向与放在同一个媒体资源中，这样方便统计和计算，不知道这其中有没有什么坑

**Comment by rchunping** [comment]
因为网站统计的是pageview

这个小程序ga当时设计的时候是参考ga安卓的客户端，统计纬度是screen

还是新建媒体资源分开吧

**Comment by algery** [comment]
感谢！仔细看了一下文档，确实是需要分开
