### ISSUE TITLE
为什么在谷歌谷歌统计中数据（页面、场景值）没有实时更新

### ISSUE THREAD

**Issue by proc07** [rchunping/wxapp-google-analytics#15]
之前还是好好的，不知道为什么今天就实时数据没有了

**Comment by rchunping** [comment]
具体是哪个统计
Acquisition > Sources > All  ?

**Comment by proc07** [comment]
Acquisition > Sources > All    
real-time
events
screens

24号时候 Acquisition > Sources > All    访问一直都没数据过来，但是今天看的话就出现了几条24号的数据。
今天 real-time 和 Acquisition > Sources > All   部分有些数据可以被统计到，但是有些又没有。

**Comment by rchunping** [comment]
我这里都正常，有些数据有延迟也正常。

如果和平时差的比较多，你检查一下你的转发服务器有没有异常

**Comment by proc07** [comment]
问过后端了，那边说没有报错之类的。之前还好好的

**Comment by rchunping** [comment]
再测试测试看看，比如你访问一下某个页面，realtime里面看看会不会出现。排除一下转发服务器的问题。

数据延迟偶尔会碰到，但是基本上过一天就好了。

**Comment by proc07** [comment]
好的，谢谢你

**Comment by proc07** [comment]
![image](https://user-images.githubusercontent.com/16809535/67537879-d87ab000-f70f-11e9-86c1-78e25418ebef.png)
hi 你知道为什么数据中会出现这种情况吗，文档说好像是没传入 utm_medium 值，但是在代码中只有一个入口限制处理了。但是还是会出现 (direct) / (none)。

**Comment by rchunping** [comment]
应该是没有来源信息，就是小程序没有提供 options.scene

我这边也有少量这种情况 2%左右

**Comment by proc07** [comment]
![image](https://user-images.githubusercontent.com/16809535/67539648-660cce80-f715-11e9-9913-809a85103ac5.png)
但是判断中已经限制了呢，scene 必须存在才能执行函数的。

**Comment by rchunping** [comment]
对啊，所以if里面的没有执行，那么这些session的客户就没有utm_medium之类的信息来表示来源
