### ISSUE TITLE
checkout and purchase 如果一次性添加多个product

### ISSUE THREAD

**Issue by hanwesh** [rchunping/wxapp-google-analytics#2]
checkout和purchase这两个action 如何一次性的加入多个不同的products？如何实现addProducts 方法？
thanks

e.g.
var product =  new Product()
    .setId("P12345")
    .setName("Android Warhol T-Shirt")
    .setCategory("Apparel/T-Shirts")
    .setBrand("Google")
    .setVariant("Black")
    .setPrice(29.20)
    .setCouponCode("APPARELSALE")
    .setQuantity(1);
var productAction = new ProductAction(ProductAction.ACTION_PURCHASE)
    .setTransactionId("T12345")
    .setTransactionAffiliation("Google Store - Online")
    .setTransactionRevenue(37.39) // 【重要】这个是订单总价，包含了 税费 和 运费
    .setTransactionTax(2.85)
    .setTransactionShipping(5.34)
    .setTransactionCouponCode("SUMMER2013");
var builder = new HitBuilders.ScreenViewBuilder()
###     .addProduct(product)
    .setProductAction(productAction);

var t = getApp().getTracker();
t.setScreenName("transaction");
t.send(builder.build());

@rchunping

**Comment by rchunping** [comment]
.addProduct(product) 可以调用多次的

builder.addProduct(prd1).addProduct(prd2).setProductAction(prdAction)
