### ISSUE TITLE
合法域名失败

### ISSUE THREAD

**Issue by glore** [rchunping/wxapp-google-analytics#3]
小程序后台添加合法域名失败， 提示未备案， 请问有什么解决方案吗？
https://www.google-analytics.com （未备案）

**Comment by rchunping** [comment]
可能现在小程序域名检测更严了

那只能用自己的备案域名反代了，配置nginx

假设你有一个已备案域名  example.com ，随便开个二级域名ga-proxy.example.com 做反代吧

```nginx
server {    
   listen 443 ssl;
   server_name ga-proxy.example.com;
   
   ssl on;
   # 设置ssl证书（略）

    location / {

      # 告诉ga用户真实ip
      # 方法1 （主动提供用户ip，但是remote_addr可能不是真实地址）
      rewrite ^(.*)$   $1?uip=$remote_addr    break;
    
      # 方法2 （告诉ga，你只是一台代理服务器，让ga自己检测用户真实 ip）
      proxy_set_header   Host       www.google-analytics.com;
      proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;


        # Proxy to google-analytics.com
        proxy_pass https://www.google-analytics.com;
    }
}
```

不过有个问题，这里需要带上用户真实的ip地址，配置里有2个方法你可以试一下哪一个管用。


**配置没有实际测试过，只提供一下思路**

**Comment by rchunping** [comment]
另外，测试的时候记得把ga.js中两个地方的 ```https://www.google-analytics.com``` 改成你自己的域名

**Comment by glore** [comment]
还是没有效：二种方式都 得出   对应的服务器证书无效。控制台输入 showRequestInfo() 可以获取更详细信息。

**Comment by glore** [comment]
showRequestInfo() 如下， 我自己的业务域名就正常http://spark.ufutx.net

**Comment by glore** [comment]
可以了， 谢谢！方法2域名显示的服务器的地址， 方法1可以显示实际地址
