### ISSUE TITLE
GA ScreenView 无数据

### ISSUE THREAD

**Issue by alexayan** [rchunping/wxapp-google-analytics#6]
GA 后台概览中只看到 Event 打点，没有 ScreenView 打点。

**Comment by rchunping** [comment]
Network里观察一下有没有类似的请求

v=1&cid=41265192-e44b-4814-1234-98d70a0adef1&ds=app&ul=zh_CN&de=UTF-8&sd=24-bit&je=0&an=sssss&av=v0.0.1&sr=750x1206&vp=375x603&ua=Mozilla%2F5.0%20(iPhone%3B%20CPU%20iPhone%20OS%2010_0_1%20like%20Mac%20OS%20X)%20AppleWebKit%2F602.3.12%20(KHTML%2C%20like%20Gecko)%20Mobile%2F14C92%20MicroMessenger%2F6.6.3&tid=UA-134355-19&cd=%2Fpages%2Flist&cs=abddsfa&cm=1001%3A%E5%8F%91%E7%8E%B0%E6%A0%8F%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%BB%E5%85%A5%E5%8F%A3&t=<b>screenview</b>&qt=0&z=537173314

**Comment by alexayan** [comment]
v=1&cid=05b9ad58-869c-4de6-8e6d-2d1206cb3616&ds=app&ul=zh_CN&de=UTF-8&sd=24-bit&je=0&an=%E6%8A%BD%E5%A5%96%E5%8A%A9%E6%89%8B%E5%B0%8F%E7%A8%8B%E5%BA%8F&av=0.1.10&sr=750x1110&vp=375x555&ua=Mozilla%2F5.0%20(iPhone%3B%20CPU%20iPhone%20OS%2010_0_1%20like%20Mac%20OS%20X)%20AppleWebKit%2F602.3.12%20(KHTML%2C%20like%20Gecko)%20Mobile%2F14C92%20MicroMessenger%2F6.6.3&tid=UA-115768895-1&cd=index&cs=%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%9C%BA%E6%99%AF&cm=1001%3A%E5%8F%91%E7%8E%B0%E6%A0%8F%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%BB%E5%85%A5%E5%8F%A3&t=screenview&qt=1&z=927952177

**Comment by rchunping** [comment]
你从实时报告里看一下，我这边过几秒就能出现

**Comment by alexayan** [comment]
找到原因了，是 GA 后台配置的问题
